### ISSUE TITLE
wine 如何自动屏蔽多余的窗口呢，而不是每次手动进行

### ISSUE THREAD

**Issue by WhiteStarx** [yundantianchang/wmctrl#2]
wine 如何自动屏蔽多余的窗口呢，而不是每次手动进行

**Comment by yundantianchang** [comment]
我一般是打开wine相关的程序后手工运行一下相应的脚本，自动屏蔽需要写点程序，可以考虑基于本项目进行二次开发。

**Comment by WhiteStarx** [comment]
感谢您的回信，最后我有写一个愚蠢的脚本实现该功能，且不稳定
